# Generated by Django 5.1.5 on 2025-02-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='api.team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to='avatars/'),
        ),
    ]
